### PR TITLE
Microbit 2023-03-25

### PR DESCRIPTION
**Pull request by mdpadberg**
Microbit 2023-03-25 including github action to generate a page

### CODE REVIEW

**Comment by teobais** [comment]
thanks @mdpadberg , anyone from the microbit team w/ a GitHub account to perform a review on this PR?

**Comment by mdpadberg** [comment]
Yes here are the accounts: @mthoolen @Rebaf @Nevets87 @tonvanbart @jvrhenen

**Comment by teobais** [comment]
thanks @mdpadberg - invited all accounts above. Let's have at least one review before merging

**Review by mthoolen — APPROVED** [review]
Proven to work in production

**Pull request merged**
